### ISSUE TITLE
Should `layout` be removed?

### ISSUE THREAD

**Issue by robb** [robb/Cartography#143]
Seems like `constrain` with a manual `view.layoutIfNeeded` is a better practice and would allow reducing the API surface quite a bit.

**Comment by kazmasaurus** [comment]
:+1:

I imagine `constrain` / `layout` usage changes from project to project, but all of the projects I work in _only_ use `constrain`. In these projects, almost every view builds constraints on `init` and then leaves the layout system to do it's thing.

I also like that this encourages Cartography to be used as a tool to create Auto Layout constraints, instead of a tool to "do layout".

**Comment by robb** [comment]
Closed by #146
