### ISSUE TITLE
Question about align function with parent view and child view

### ISSUE THREAD

**Issue by JackieQi** [robb/Cartography#178]
Hi @robb , first i want to thank you for the brilliant work. I encountered a problem when using align function with superview and child view. Here is my code snippet

```swift
constrain(tableView, resetButton, closeButton, view) { tableView, resetButton, closeButton, view in
      resetButton.top == view.top
      resetButton.leading == view.leading
      resetButton.width == 60
      resetButton.height == 30

      align(top: closeButton, resetButton)
      //closeButton.top == resetButton.top

      closeButton.width == 60
      closeButton.height == 30
      
      tableView.top == resetButton.bottom + 10
      tableView.width == view.width
      tableView.bottom == view.bottom
      tableView.centerX == view.centerX
      
      closeButton.trailing == view.trailing
      //align(trailing: closeButton, view)
    }
```

The layout i want to get is like this

So i have a simple view, with two buttons on top "reset" and "close", and there is a tableview under the button with 10px padding in between.

![img_0013](https://cloud.githubusercontent.com/assets/358367/10855038/b3ab5f98-7efc-11e5-8145-28b3a58785c2.PNG)

However, when i uncomment the last line of the code snippet, that is if i use 
`align(trailing: closeButton, view)` instead of `closeButton.trailing == view.trailing`
the layout is not populated correctly, because the view will not have width and height information in final layout. Here is the constrains layout screen shots for these two different code:

| Expected        | Wrong  |
| ------------- |-------------|
|  ![expected](https://cloud.githubusercontent.com/assets/358367/10855234/b6486e02-7efd-11e5-83aa-82f3e8cadf7f.png)  | ![error](https://cloud.githubusercontent.com/assets/358367/10855247/c4982146-7efd-11e5-9447-cfdc428e355b.png) | 

Thanks very much for your time in advance.

**Comment by ozgur** [comment]
Same problem here. It happens only when using `align()` with a view and its superview. Not with siblings.

**Comment by ozgur** [comment]
Same problem here. It happens only when using `align()` with a view and its superview. Not with siblings.

**Comment by kazmasaurus** [comment]
What's happening is that the operators and the `align` functions have slightly different behaviors around setting `translatesAutoresizingMaskIntoConstraint`.
- Operators sets `translatesAutoresizingMaskIntoConstraint = false` for any item on the left hand side as stated in the [README](https://github.com/robb/Cartography#usage).
- `align` sets `translatesAutoresizingMaskIntoConstraint = false` for _all_ items passed to the function, which is currently only documented in [the code](https://github.com/robb/Cartography/blob/master/Cartography/Align.swift#L25-L26).

I've ran into this problem myself when the superview is a `UIViewController`s `.view`, because `UIViewController` needs it's `.view` to have `translatesAutoresizingMaskIntoConstraint` on in order for it to lay everything out properly.

In cases where you want to use `align` on a VC's view, you can set `translatesAutoresizingMaskIntoConstraint` back to `true` _after_ the `constrain`.

**Comment by JackieQi** [comment]
@kazmasaurus :+1:   Thanks very much. That's the cause! It works well after i do `view. translatesAutoresizingMaskIntoConstraint = true`
