### ISSUE TITLE
Cartography doesn't support iOS 7

### ISSUE THREAD

**Issue by michaeleisel** [robb/Cartography#52]
This is a major issue, considering only about two-thirds of the users out there are using iOS 8.

**Comment by robb** [comment]
Cartography by itself supports iOS 7.

The podspec specifies iOS 8 since I am under the impression that CocoaPods only supports Dynamic Frameworks for Swift, which in turn require iOS 8. (@orta right?)

Carthage only supports only builds Dynamic Frameworks.

You can, however, use git submodules and pull in the source files manually into your project,  or concatenate them all in a single file, if you'd prefer.

**Comment by orta** [comment]
Yep, same deal.

**Comment by michaeleisel** [comment]
Thanks, I'll do that then :)
