### ISSUE TITLE
How can I capture an Edge?

### ISSUE THREAD

**Issue by Arvkon** [robb/Cartography#79]
Is there a way to capture an Edge for use in another layout() call at a later time? I'm trying to do something like the following, but get a crash when I unwrap viewBottom.

    var viewBottom: Edge?

    layout(self.view) { view in
       view.height == ...
       view.top == ...
       viewBottom = view.bottom
    }

    layout(self.view2) { view2 in
       view2.top == viewBottom! + 10
    }

**Comment by robb** [comment]
Unfortunately, a `LayoutProxy` or its properties cannot currently outlive their layout blocks.
This is basically because the `layout` function needs to know where to look for constraints to install but properties from other blocks may not be available to it.

I wish there was a way to prevent your example from compiling, to make this behavior more obvious, but I don't there's a way for that, currently.

**Comment by Arvkon** [comment]
How about copying the value that I'm after (view.bottom)? Would that be possible?

**Comment by robb** [comment]
Not sure what you mean, but `view.bottom` isn't a value but rather a symbolic variable (after all, it's Auto Layout's job to figure out the value).

You could do this

```swift
layout(self.view) { view in
   view.height == ...
   view.top == ...
   viewBottom = view.bottom
}

layout(self.view, self.view2) { view, view2 in
   view2.top == view.bottom + 10
}
```

however.

**Comment by Arvkon** [comment]
Thanks! The solution you propose does solve my problem =)

**Comment by robb** [comment]
:ok_hand:
