### ISSUE TITLE
🚨 Subtle changes in Layout Behavior 🚨

### ISSUE THREAD

**Issue by robb** [robb/Cartography#91]
@mergesort in chat, after upgrading to 1174be88d3:

> Not sure why, but all my other layouts are now messed up.
> I'm gonna file an issue.
> But it's not looking good..

In Cartography `0.2.1`, a constraint like

```
lhs.top == rhs.top
```

would only call `setTranslatesAutoresizingMaskIntoConstraints(false)` on `lhs`, regardless of whether that view is owned by a `UIViewController`.

However, since 1174be88d3, the behavior subtly changed. `setTranslatesAutoresizingMaskIntoConstraints(false)` is now called on both `lhs` **and** `rhs`, as long as they are not the `view` of a `UIViewController`.

It only makes sense that `==` is symmetric, since that is a requirement of equality relations. However, Cartography `constrain` blocks commonly look like this:

```swift
let view == // a UIViewController.view's direct child
constrain(view) {
    view.top == view.superview!.top
}
```

That is, if a `UIViewController.view` was to show up in a constraint, it would commonly be the on right hand side and thus not have its autoresizing mask translation disabled. Unfortunately, `UIViewController` appears to depend on that being active, which required #89 in the first place.

It would be great if users of Cartography could try their code against the latest `master`, currently 8b2a52d9e0 to see if they are affected by this and check, if they can reasonably work with the new behavior.

**Comment by robb** [comment]
Hmm, the _Adopting Auto Layout_ guide paints a grim picture:

> The principal circumstance in which you should not call `setTranslatesAutoresizingMaskIntoConstraints:` is when you are not the person who specifies a view’s relation to its container. For example, an `NSTableRowView` instance is placed by `NSTableView`. It might do this by allowing the autoresizing mask to be translated into constraints, or it might not. This is a private implementation detail. Other views on which you should not call `setTranslatesAutoresizingMaskIntoConstraints:` include an `NSTableCellView` object, a subview of `NSSplitView`, a view of `NSTabViewItem`, or the content view of an `NSPopover`, `NSWindow`, or `NSBox` object.

So unless we want to maintain an epic black list, it would seem like we shouldn't call `setTranslatesAutoresizingMaskIntoConstraints` at all, even though it's what the user wants 90% of the time?

**Comment by robb** [comment]
I gave this some thought and I'm currently leaning towards not calling `setTranslatesAutoresizingMaskIntoConstraints` at all, since it's ultimately an implementation detail of the view and Cartography can't know for sure what's appropriate to do. :unamused: 

We can, however, make it more convenient by adding something like

```swift
stopTranslatingAutoresizingMaskIntoConstraints(view: View...)
```

which allows turning off the behavior for multiple views at once. The example from the Readme would thus turn into 

```swift
stopTranslatingAutoresizingMaskIntoConstraints(view1, view2)

layout(view1, view2) { view1, view2 in
    view1.width   == (view1.superview!.width - 50) * 0.5
    view2.width   == view1.width - 50
    view1.height  == 40
    view2.height  == view1.height
    view1.centerX == view1.superview!.centerX
    view2.centerX == view1.centerX

    view1.top >= view1.superview!.top + 20
    view2.top == view1.bottom + 20
}
```

At least this only needs to be called once in the whole lifetime of a view.

**Comment by robb** [comment]
@smileyborg Do you happen to have any insights here that you gained from PureLayout?

**Comment by smileyborg** [comment]
Nice title on this issue, @robb :smile:

As far as which views to implicitly call `setTranslatesAutoresizingMaskIntoConstraints:NO` on, I originally added similar functionality to PureLayout's predecessor, UIView+AutoLayout, [in this commit](https://github.com/smileyborg/UIView-AutoLayout/commit/9dfd5400befc76b068eeb7be5e76703541df5e84). In the commit message I described a little bit about the approach taken.

Basically, I found that it only made sense to change this value on views being sent the layout message (in other words, the `lhs` view in Cartography). The main reason I came to this conclusion is because I had numerous places where I would mix auto layout and non-auto layout views (sometimes it's just easier to use the autoresizing mask, or you want to do animations or interactions that just don't play well with auto layout). In these mixed cases, I found that the `lhs` view was always the one using auto layout, whereas the `rhs` view may or may not be (as you note, it could be a table view cell's contentView, or a view controller's view, etc). And in the cases where both the `lhs` and `rhs` were auto layout views, I found that there was always some other layout constraint where the `rhs` view was used in the `lhs` -- meaning, it would get `translates...` set correctly at that point.

I definitely tried to err on the conservative side. I haven't seen a single issue (from myself or anyone else) about this behavior, and it was implemented ~9 months ago, so at this point I'm pretty comfortable saying it's probably the right way to do it. Trying to maintain a blacklist or whitelist of views is definitely going to be an exercise in futility :stuck_out_tongue:.

I do encourage use of [these](https://github.com/smileyborg/PureLayout/blob/master/PureLayout/PureLayout/ALView%2BPureLayout.h#L44) [methods](https://github.com/smileyborg/PureLayout/blob/master/PureLayout/PureLayout/ALView%2BPureLayout.h#L47) when creating views you know will use auto layout. But the implicit behavior above helps if you forget to do that.

Let me know what you think.

**Comment by smileyborg** [comment]
A side note, I don't think your reasoning about the `==` operator (as used here in Cartography) being "symmetric" is accurate. Because of how it gets translated down into a linear equation in the constraint, there is a difference with whether a view is on the left or right side. Your `==` is just syntactic sugar for that, not a true "equality".

**Comment by robb** [comment]
Yeah, I wonder if it's best to formalize this through the type system so that

```
property == expression | property | numerical constant
```

is the only form Cartography works with. Symmetry would be nice but it's a fight against Auto Layouts windmills :pensive:

**Comment by robb** [comment]
@smileyborg thanks for the insights :sparkling_heart:

**Comment by smileyborg** [comment]
You're welcome! Cartography is definitely my favorite take on auto layout, for those who have the luxury of working in a pure-Swift world.

**Comment by robb** [comment]
Closing this one out in favor of #94
